### ISSUE TITLE
Register services that don't have ports

### ISSUE THREAD

**Issue by yarmiganosca** [joyent/containerpilot#117]
We're building a tool that makes heavy use of containerbuddy and the autopilot pattern to essentially "do all the networking/discovery stuff" for apps. We're running containerbuddy in every container built for the apps, and in every container they depend on (db, cache, whatever). So far working with containerbuddy has been amazing! We'd like to fit long-running async tasks (kafka consumers in particular) into this paradigm. Registering these "services" with a port doesn't really make sense, but the dependency discovery _is_ something they need, and I'd very much like to only write that once. Consul itself doesn't require port information to be provided with a service definition (https://www.consul.io/docs/agent/services.html), so I was hopeful not providing a port number in a service definition would be supported. However, containerbuddy currently doesn't support the registration of services that don't supply a port number. Can a port number be made optional?

**Comment by tgross** [comment]
@yarmiganosca I'm glad to hear you're finding Containerbuddy useful!

> Can a port number be made optional?

I took a look at the code and there are two pieces to making this happen. We currently [validate that the port is non-zero](https://github.com/joyent/containerbuddy/blob/46641555861a137fbf1866931c2df6f2ae94af09/containerbuddy/config.go#L309-L312), and we could certainly remove that check or make it check for non-negative and that would work. The other item is that Hashicorp's Consul golang client will end up with a default value of 0 for the port if it isn't specified (because [`AgentServiceRegistration`] takes an int). I haven't yet tried it yet to see what actually happens in Consul if you pass a zero value there. Should be easy enough to test (and if you feel like working it up I'd be happy to get it in).

That being said, if you're not advertising the service on a port, you can actually just leave off the `services` stanza entirely and it won't register services, just check for changes to dependencies, etc.

**Comment by yarmiganosca** [comment]
I didn't realize the service stanza was entirely optional. Just tried it and that worked just fine. Thanks for the suggestion!

**Comment by tgross** [comment]
Ok, glad you have a workaround for the time being. I think the option to have a no-port-advertised service would be useful though, so I'm going to leave this issue open and suggest that it would be a good item for someone from the community who's looking for an easy way to get involved to add.

**Comment by tgross** [comment]
This issue becomes unnecessary once we implement https://github.com/joyent/containerpilot/issues/245 because of the separate of service and health check. We also haven't had anyone ask about it again, so I don't think it's a use case we especially need to support. Closing.
