### ISSUE TITLE
Set canonical import path

### ISSUE THREAD

**Issue by blakewhite** [joyent/containerpilot#127]
I'm using containerbuddy with other go apps. As such I'm attempting to build very lightweight images with CenturyLink's golang-builder. It requires the canonical path to be set. I can edit my local source for containerbuddy, but figured you would want to get that set up to something you had more control over than the github link.

Thanks!
Blake

**Comment by tgross** [comment]
You're talking about adding this to main.go?
`package main // import "github.com/joyent/containerbuddy"`

If I understand correctly, CenturyLink is going to be pulling master, which I would not recommend. Currently Containerbuddy is not "go gettable", so I'm honestly not sure you're going to get good results out of that in any case. What's more, golang-builder requires using _workspace directories to pin dependencies, which we're not doing here because we're using the GO15VENDOREXPERIMENT flag. If you attempt to build from HEAD of all our dependencies, you will definitely fail to get good results (the Consul lib is broken at the HEAD of master, like, all the time).

We package compiled binaries as releases. Given that you're trying to build a minimal container from the scratch image, why not add the binary with an `ADD` in your Dockerfile?

**Comment by blakewhite** [comment]
That sounds like the better path to go at this point. I don't think the builder actually performs the pull on the main package, but it does require the canonical import path to be there. I'll try just with adding binaries in and see how that performs. Thanks!

**Comment by tgross** [comment]
Ok. I would like to look into improving our ability for Containerbuddy to be built by other tools and that's a factor in the refactoring we're doing in https://github.com/joyent/containerbuddy/issues/83.

See how that goes for you and either way let me know here and we can either mark this as an enhancement or close it.

**Comment by tgross** [comment]
I've done this in https://github.com/joyent/containerbuddy/pull/123, which is under review.

**Comment by tgross** [comment]
Done and included in the 2.0 release: https://github.com/joyent/containerpilot/releases/tag/2.0.0
