### ISSUE TITLE
Support for ZooKeeper

### ISSUE THREAD

**Issue by giorgio-v** [joyent/containerpilot#142]
Are there any plans to support ZK as an alternative to Consul?

**Comment by justenwalker** [comment]
Consul is preferred since it has a more rich service-discovery story than etcd/zookeeper. Services are first-class objects and it even allows you to query them via DNS.

Zookeeper is just a filesystem, the implementation (like etcd) would be very ContainerPilot specific - there is no real standard for service discovery on these distributed filesystems.  I don't know if it is on the roadmap, but it would be possible. Probably by re-using some of the code in the etcd implementation.

I'm sure @tgross / @misterbisson would welcome a PR if you have some time to develop one 😃

**Comment by giorgio-v** [comment]
I think can work on this. No guarantees about timeframe since I’m just getting started, but if it’s something deemed useful I’d be glad to help.

**Comment by tgross** [comment]
I'd love to see a ZK backend!

I think @justenwalker has some good points about ZK's scope, but there are plenty of projects that use ZK under the hood for service discovery so I'd hope it's not impossible.

**Comment by justenwalker** [comment]
One thing that would be good to discuss before going on is the library for communicating with zookeeper.  With etcd it was a natural choice to use the official SDK since etcd is also a golang project.  

- https://github.com/samuel/go-zookeeper
- https://wiki.ubuntu.com/gozk
- Others?

I haven't looked into them. go-zookeeper is the first result in google for `golang zookeeper`. Canonical also made a library called `gozk` although I don't know if it is actively developed. There may be others?

**Comment by justenwalker** [comment]
you may want to wait for  #144 since it will affect how service discovery backends are implements. Hopefully making it a bit more straight forward. At least it will include a README.

**Comment by giorgio-v** [comment]
OK, I’ll take a look at that PR in the meantime.

**Comment by tgross** [comment]
Following up on the license issue; let's use `go-zookeeper` for the client library.

**Comment by giorgio-v** [comment]
👍

**Comment by justenwalker** [comment]
One other comment.

I've been looking into Hashicorp Vault recently, and I saw a [GH Issue](https://github.com/hashicorp/vault/issues/1367) about problems with `go-zookeeper`. Apparently, the project is either dead, or at least very stagnant. It's pretty much the only game in town for a go client, so I'm not sure we have much of a choice. Someone will likely need to fork/maintain it in the future, but so far no one has risen to the task.

**Comment by talbright** [comment]
I don't think it has been, see my comments on hashicorp/vault#1367

There's an interesting library being worked on by docker, that builds an abstraction layer on top of consul, zookeeper, and etcd. However it's pretty new. Also, it uses go-zookeeper as the provider for zookeeper.

**Comment by tgross** [comment]
> There's an interesting library being worked on by docker, that builds an abstraction layer on top of consul, zookeeper, and etcd. 

I'd hate to bind ourselves to that library only to have someone really want to drop in support for Eureka or (an experiment I've thought of) Redis pub/sub.

I'd be pretty happy with using a Hashicorp fork of go-zookeeper if they decide to go that route.

**Comment by talbright** [comment]
> I'd be pretty happy with using a Hashicorp fork of go-zookeeper if they decide to go that route.

Me too. I'm talking with them to see if I can convince them to do that.

**Comment by tgross** [comment]
We're going to close this issue, as ContainerPilot v3 is consolidating on Consul.

**Comment by pmoust** [comment]
@tgross just to clarify, is containerpilot now bound to _just_ Consul?
In the [FAQ](https://www.joyent.com/containerpilot/docs/faq) it is stated that
> The service catalog that ContainerPilot looks up and registers services in is pluggable. Consul and Etcd are supported now, there is discussion of ZooKeeper as well.

**Comment by misterbisson** [comment]
The FAQ is accurate for 2.x and 3.x, but we've been struggling to find a way to leverage the many valuable features only available in Consul while remaining catalog agnostic. 

In the end, we finally had to admit that our agnosticism on this point was holding ContainerPilot back, not adding value. ContainerPilot 3.x, now in development, will natively leverage those Consul-only features.
