### ISSUE TITLE
preStart a background process like consult template

### ISSUE THREAD

**Issue by richard-mauri** [joyent/containerpilot#157]
Currently we are using a task to periodically (like 1m) run consul-template -once ... to generate an nginx config with all our discovered services in consul. This works, but at cost of lots of process thrashing. We think it should be better; like having consul template long running with a wait interval instead.
Now, the list of services is not known ahead of time so using onStart to kick off consul template and onChange for each service is not appropriate.

Is there or can there be a way to have like preStart launch a bg process like consultemplate with samelifeycle as the shimmed app (in our case nginx) ?

**Comment by justenwalker** [comment]
@richard-mauri : Seems like [tasks](https://github.com/joyent/containerpilot#tasks-optional) will do what you want. You could combine tasks and preStart to run the same command, so that preStart runs first to set up the correct environment, and then tasks keeps it current.

**Comment by justenwalker** [comment]
Nevermind my last comment (delete to avoid confusion.)  You are running consul-template using tasks already.

Seems what you want to do is counter to how docker containers are typically constructed - namely they really should only have 1 daemon process running at a time.

You might be able to daemonize your process as part of the preStart script though through so it continue to run - however it's life-cycle will not be managed by ContainerPilot so if it dies, it won't get restarted.

**Comment by justenwalker** [comment]
Also, When you say "This works, but at cost of lots of process thrashing." - what is the effect of this?

**Comment by tgross** [comment]
I'm in agreement with @justenwalker on this one but I'm also curious as to the effects you're seeing in terms of process thrashing. If we're talking about 1 min intervals I'm having trouble imagining this is causing resource issues (other than any hypothetical issues that `consul-template` itself might be having).

**Comment by richard-mauri** [comment]
Just to be more clear; we are not experiencing any adverse problems with having "tasks" periodically exec consul template; it is a hypothetical concern at this point. Certainly decreasing the interval of the task in an attempt for our service discovery and nginx config rewrite may reach a point where the overhead of an exec model will start to "thrash". I am considering an approach to change the main container pilot process to be a process that itself execs consul template (as a singlelong running process) and also execs nginx. To the others that think what I'm doing vilates docker container as a single process don't get containerpilot. To me it's more like a logical process than an actual single process. I'm also wondering about having containerpilot supporting a list of processes instead of one. In that way I don't have to build my layer in between. I'm sure others will note the benefit.

**Comment by dissipate** [comment]
I'm in a similar situation as Richard (I want to run Consul Template in
daemon mode), and the restriction of just having 1 startup script is what
is keeping me from using ContainerPilot currently. I agree with the idea of
having 1 process per container, but I interpret this as 1 *main* process
per container. Often, you need 'sidecar' type processes like ConsulTemplate
in addition to your main process. ContainerPilot should support the ability
to daemonize any number of processes, IMO. If it runs as PID 1 and it's
already supporting 1 startup script, why not more than 1?

Right now I'm looking at having to use Runit (http://smarden.org/runit/) to
spin up ConsulTemplate as well as my main process and then ContainerPilot.
This doesn't really make sense as it is overly complex, and developers are
not going to want to do this. If ContainerPilot offered similar
functionality as Runit, then I would just run ContainerPilot and the
problem goes away.

Steven

**Comment by richard-mauri** [comment]
Thanks for all participating in this thread so far. I want to share another idea that a colleague suggested is to ditch the consul template polling approach altogether and some how participate in the "gossip protocol" and receive events when services come and go from consul....

**Comment by dissipate** [comment]
Richard,

   That's interesting. Any idea on how that could be achieved without
application level changes? We are using Consul Template because we don't
have to make application changes. Any application that slurps in a config
file is supported.

Steven

**Comment by tgross** [comment]
@richard-mauri wrote:
> I'm also wondering about having containerpilot supporting a list of processes instead of one. 


@dissipate wrote:
> ContainerPilot should support the ability
to daemonize any number of processes, IMO. If it runs as PID 1 and it's
already supporting 1 startup script, why not more than 1?

From a design standpoint, ContainerPilot provides the responsibilities we think an *application container* needs. If you need to run multiple processes inside a container you absolutely should be using a real supervisor (runit is a great example), and arguably you should not be using Docker for this at all. The ecosystem of tooling around application containers expects process exit codes and stdout/stdin to be preserved. By bundling multiple non-inheriting processes together under the same tree you're going to break the expectations of the container runner.

Let's ignore ContainerPilot for a moment and look at a simple example. You're running a Docker container with Postgres and consul-template in daemon mode, both started by runit. If consul-template fails and exceeds the restart limit from runit, what are we supposed to do with the process tree? Restart the whole container at that point? What happens to Postgres now? What exit code do we get in our container runtime (our scheduler or even just `docker run`)?

Now let's suppose for the moment that we're willing to give up the expectations of our container runtime and put this stuff into ContainerPilot. We now have to add this scope to ContainerPilot and we have to make decisions about the init behavior, which expands the amount of configuration we need to do. How do we handle `preStart`, `preStop`, `postStop` behaviors relative to the number of application process trees we're running? There's a ton of complexity added here.

That being said, if you're going to build a multi-process container and want ContainerPilot (for example, a Joyent infrastructure container as I've seen someone do), then you can still use ContainerPilot to provide service registration, TTL heartbeat, telemetry, etc. Just run it as a "wrapper" for the service you care about and then have your various secondary processes run under the supervisor. Your process tree might look like this:

```
runit
|_ containerpilot
|   |_ health.sh
|   |_ postmaster
|       |_ postmaster
|       |_ postmaster
|       |_ postmaster
|_ consul-template
```

---

@richard-mauri wrote:
> I want to share another idea that a colleague suggested is to ditch the consul template polling approach altogether and some how participate in the "gossip protocol/serf" and receive events when services come and go from consul.... Or maybe consul "watches".

I've toyed with this idea as library code for a personal project and ultimately where you end up going is just having the application participate in the Consul raft as an agent. In theory is this actually pretty darn cool, but it excludes existing applications. It's also all but impossible to do in a portable way where we could support etcd and the other backends we want to support for ContainerPilot, but it's an interesting technique.

**Comment by justenwalker** [comment]
> That being said, if you're going to build a multi-process container and want ContainerPilot (for example, a Joyent infrastructure container as I've seen someone do), then you can still use ContainerPilot to provide service registration, TTL heartbeat, telemetry, etc. Just run it as a "wrapper" for the service you care about and then have your various secondary processes run under the supervisor. Your process tree might look like this:

I agree with @tgross here.  ContainerPilot implemented process reaping only to be a good unix citizen when it assumes the responsibility of PID1 inside a container. PID1 doesn't imply a full-fledged init system. If you do need one - there are many options, including those built for docker.  The [phusion image](https://github.com/phusion/passenger-docker) is a good start if you want to go this route.

**Comment by dissipate** [comment]
Tim,

   I am aware of the issues that you are pointing out, and I have read some
of the back-and-forth between say the guys at Phusion who believe in
multi-process containers and others who believe in single process
containers. It's a classic case of purity vs. pragmatism. In my opinion,
the multi-process camp is going to win the war. Not because they are
correct on the matter (that's still open for debate), but simply because
developers are not going to adhere to the single process rule. I have
considered the scenario you have proposed, where Runit spins up
containerpilot and consul-template, but it seems like it might be overly
complex. I haven't decided either way though, so I will probably try it to
see how it goes. I see your reasons for not adding multi-process
functionality to ContainerPilot (it opens up a can of worms). In my case, I
am actually not relying so much on exit codes from the actual containers,
but rather from the health checks. After all, a process could be totally
fubar for more complex reasons that might not trigger an exit (e.g. bad
health of downstream services) and the container could still be running.
This is probably much more amenable to web-based processes where health
check endpoints are expected to be available (if you can't curl /health,
something is wrong). A command-line-based process, not so much. If I were
to do a command-line-based container where a user is running the container
on the command line, passing arguments and expecting a result, I would put
a lot more effort into making sure the exit codes were correct, and I would
almost certainly adhere to the 1 process-per-container rule.

Steven

**Comment by tgross** [comment]
> I am aware of the issues that you are pointing out, and I have read some of the back-and-forth between say the guys at Phusion who believe in multi-process containers and others who believe in single process containers. It's a classic case of purity vs. pragmatism. In my opinion, the multi-process camp is going to win the war. 

There is no war -- at Joyent we've been running multi-process containers in production for roughly a decade. Each has their place. But the developer ergonomics you're concerned about are facilitated by the single-process model as that's precisely what caused Docker be so successful. That being said, this is entirely off-topic. 😀 

ContainerPilot is intended to support an [app-centric micro-orchestration](https://www.joyent.com/blog/app-centric-micro-orchestration). This means that it's supporting the application, not an entire user-land. That this is in Docker is incidental; it's entirely possible to shim a non-Docker application using ContainerPilot. The Autopilot Pattern is agnostic to whether you're running single-process, multi-process, or under VMs.

It looks like we're in agreement that this is a usage discussion at this point? Maybe the debate would be better moved to the gitter chat rather than cluttering up issues.

**Comment by justenwalker** [comment]
> In my case, I am actually not relying so much on exit codes from the actual containers,
> but rather from the health checks.

ContainerPilot doesn't need to run the service to do health checks. You can have one or more service definitions with their own health checks monitoring services that, for instance, runit is managing.

**Comment by tgross** [comment]
Ok, looks like we've agreed in the gitter chat that this is a usage issue rather than something we want to add. I'm going to close this issue.
