### ISSUE TITLE
Consul backend does not support URL path

### ISSUE THREAD

**Issue by ric03uec** [joyent/containerpilot#158]
we're running a consul server behind an custom api so the url provided to `containerpilot` in the config file is of type
```
{
    "consul" : "localhost:5000/consul",
}
```
upon starting `containerpilot` after this setting, i get the following error
```
2016/05/16 16:07:41 Put http://localhost:50000%2Fconsul/v1/agent/check/pass/sauron-demoapp-crossbow?note=ok&token=<sometoken>: dial tcp: unknown port tcp/50000/consul
Service not registered, registering...
2016/05/16 16:07:41 Service registration failed: Put http://localhost:50000%2Fconsul/v1/agent/service/register?token=<sometoken>: dial tcp: unknown port tcp/50000/consul
2016/05/16 16:07:41 Check registration failed: Put http://localhost:50000%2Fconsul/v1/agent/check/register?token=<sometoken>: dial tcp: unknown port tcp/50000/consul
```
However, if use `nginx` to redirect the traffic to `localhost:8500` to `localhost:5000/consul`, it works as expected. the following is `nginx` config file for this setup
```
server {
        listen 8500;

        server_name localhost;

        location / {
        proxy_pass          http://127.0.0.1:50000/consul/;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-for $remote_addr;
        }
}
```

I want to be able to point `containerpilot` directly to the desired endpoint and have it connect there. Is this a bug or am i missing something obvious here.
thanks

**Comment by tgross** [comment]
> "consul" : "localhost:5000/consul"

The reason this configuration doesn't work because the field value for Consul is an address, not a URL. The Hashicorp Consul client [doesn't accept a path component](https://github.com/hashicorp/consul/blob/75010d1924fd68e5e32b891b9a4e0a75932ac6e8/api/api.go#L172-L179).

There's not really a way for us to provide this behavior without forking the Hashicorp client or getting them to change the behavior, and from an API design standpoint I could see why they wouldn't want to do this. We should probably be giving you a better error message though and if you do some spelunking into the private functions it looks like [our naming of these functions](https://github.com/joyent/containerpilot/blob/3f7f6b83f9128b2a7b05117edebf69e4574b2efb/discovery/consul/consul.go#L69-L75) could use some improvements.

Can I ask what the use case here is? Why do you need a path component to the address, if only one service can be listening on that port anyways (i.e. under your config Consul will be the only thing listening on port 50000)? Do you have some kind of proxy in front of Consul that needs the path component?

**Comment by ric03uec** [comment]
@tgross 
you guessed it right. `consul` is running behind a proxy that is serving other functionality also. The uber service listens on port 5000 and the `/consul` proxies the request to one of the `consul` agents. We're adding some custom logic based on the intercepted `token` value from `containerpilot` requests because of which this had to be structured in this manner. Also, we didn't want to add an additional service just for this purpose so adding another route made more sense.
based on the use case, is there any other recommended way of achieving this or i should stick to the solution i mentioned in my previous comment?

**Comment by tgross** [comment]
I did a bit more digging and it turns out this is an open issue for the Hashicorp Consul API: https://github.com/hashicorp/consul/issues/1382. There are workarounds shown in both Nginx and HAProxy in that issue.

As for suggestions... well in https://github.com/joyent/containerpilot/issues/153 we discussed how the Consul client passes along the `X-Consul-Token` header. Could you use the presence of this token to do your routing logic instead of the path? I don't know enough about the proxy "uber service" you have and how it's configured, so take any suggestion I have with a pinch of salt.

---

*crazy person's approach below, feel free to ignore*

Alternately, depending on how much hacking you feel like doing, it looks like all the URLs that the Consul client uses are [hard-coded](https://github.com/hashicorp/consul/blob/75010d1924fd68e5e32b891b9a4e0a75932ac6e8/api/agent.go#L126) but every one of them passes thru the [`newRequest` function](https://github.com/hashicorp/consul/blob/75010d1924fd68e5e32b891b9a4e0a75932ac6e8/api/api.go#L438-L460). If you injected a prefix into the path at that point (by forking your own Consul client and building your own ContainerPilot with it) you could override Consul's behavior. Given that https://github.com/hashicorp/consul/issues/1382 is open it's feasible that you could get this sort of behavior accepted upstream too.

**Comment by tgross** [comment]
Updated the title to "Consul backend does not support URL path" (was "custom consul endpoint failing") so that it'll be a clear use case in hashicorp/consul#1382

**Comment by tgross** [comment]
Closing in lieu of the open Consul issue.
