### ISSUE TITLE
Please confirm the policy of backend service status

### ISSUE THREAD

**Issue by fastpopo** [joyent/containerpilot#160]
"consul.go - CheckForUpstreamChanges()", 

in the code, when the first time for checking backend service status, if the backend service already on, the operation always return true. 

do you have any rules about it?

**Comment by tgross** [comment]
That's correct. The reason being that the initial list of addresses will be empty and after the first check it will be full. This ensures that the first time we check for backends that we run the `onChange` handler so that the application has this information when it first runs.

For example, if you have an application that has a database, it will start without having hostname for that database. If we didn't fire the `onChange` handler, then the configuration file that the application uses to configure that endpoint won't have been populated.

**Comment by fastpopo** [comment]
@tgross thanks for your explain. :+1:
