### ISSUE TITLE
Multiple ports

### ISSUE THREAD

**Issue by thefosk** [joyent/containerpilot#187]
Some services listen on multiple ports, but the JSON configuration file only allows to specify one port.

**Comment by tgross** [comment]
The typical way to handle that is to have multiple service blocks, one for each port. This also allows you to ensure that health checks are being made for each of the service ports.

**Comment by tgross** [comment]
Just following up on this. Because we're registering the IP and port with the discovery catalog, we can't have multiple ports for a service -- there'd be no way for other services to differentiate between the various ports for a single service. For example, if we extended the config syntax so that we could do:

```
{ "services": [
  {
    "name": "example",
    "ports": [8000, 9000]
  }
]}
```

Then when another service queries Consul at `/v1/health/service/example` it'll get a JSON body back like:

```json
[
  {
    "Node": { ... },
    "Service": {
      "ID": "example-abcdef",
      "Service": "example",
      "Tags": null,
      "Address": "10.1.10.12",
      "Port": 8000
    },
    "Checks": [ ... ]
  },
  {
    "Node": { ... },
    "Service": {
      "ID": "example-abcdef",
      "Service": "example",
      "Tags": null,
      "Address": "10.1.10.12",
      "Port": 9000
    },
    "Checks": [ ... ]
  }
]
```

which means we can't differentiate between the two. We could further extend the syntax to allow an assignment of each port to a different name, but to fully define this we just end up having multiple service blocks anyways, which was the original workaround I suggested in https://github.com/joyent/containerpilot/issues/187#issuecomment-233412662.

I'm going to close this issue but feel free to re-open if you think it needs further discussion @thefosk
