### ISSUE TITLE
Use variables from preStart script in docker command?

### ISSUE THREAD

**Issue by bborysenko** [joyent/containerpilot#192]
Is there is some way to use variables from preStart script in docker command? What i'm trying to achieve is to get list of Percona nodes  in preStart:

```
export WSREP_CLUSTER_ADDRESS=$(curl -s 'http://192.168.99.100:8500/v1/health/service/db?passing' | jq -r '[.[].Service.Address]|sort|join(",")')
```

and join a new container to the cluster:

```
CMD containerpilot mysqld --user=mysql \
--wsrep_cluster_address="gcomm://$WSREP_CLUSTER_ADDRESS" \
...
```

Thanks in advance.

**Comment by justenwalker** [comment]
@bborysenko Typically, you chose a shell script as your entrypoint in this case instead of running the application itself.  

For example:

```bash
#!/bin/bash
export WSREP_CLUSTER_ADDRESS=$(curl -s 'http://192.168.99.100:8500/v1/health/service/db?passing' | jq -r '[.[].Service.Address]|sort|join(",")')
exec mysqld --user=mysql --wsrep_cluster_address="gcomm://$WSREP_CLUSTER_ADDRESS" 
```

Notice the `exec` in that script - it means replace the current process with the one we're executing - so that signals will propagate correctly.  A lot of times, this pattern is used to write a config file at start-up before executing the main application.

**Comment by bborysenko** [comment]
@justenwalker thanks!
