### ISSUE TITLE
Multiple servers design

### ISSUE THREAD

**Issue by fitz123** [joyent/containerpilot#202]
Hello everyone!

Containerpilot it's a greatest thing! Autopilotpattern - this is exactly how I see proper microservices/containers design. But after a day of pain I have a few questions

My use case is to run few similar containers with ffmpegs as a main app and nginx as co-processor. Container runs with ffmpeg parameters, ffmpeg grabs live stream and produces hls video chunks out of it, I'm using nginx to "share" them.
I spend quite a lot time trying to understand how to run few ffmpeg/nginx containers on the same host, having consul-cluster and load balancer on another accordingly "autopilotpattern". but I gave up.

Major issues:

1. Using _--network bridge_ seems there's no way to find out host's IP adderss and mapped ports from inside container. It the "example" it works great, but inside bridged network only. In case load balancer, consul and app reside on different hosts - it doesn't work. Unless using overlay driver, but I don't like idea of additional network layer.
2. Using _--network host_ it's quite hard to run multiple consul instances: need to use uniq ports for each, generate uniq node names, and more

The best way I found is to ditch consul agents and use built-in service agent communicated directly with consul server and pass variable for Nginx Port (and Service Port) manually during container creation.

It works fine but 2 issue don't let me sleep:

1. There's SPoF with containerpilot, which uses only 1st resolved IP address of Consul cluster. Need to perform additional tasks to make eliminate it, like create failover (carp) load balancers in front of consuls or to use docker 1.12 swarm style load balancing from each consul to all
2. Manual ports assignment for every container quite painful

Did I miss something or there's no better way to deal with my use case?

Thank you again for the great project!

**Comment by tgross** [comment]
It's a [requirement of the Autopilot Pattern](http://autopilotpattern.io/#what-infrastructure-do-we-need) to have overlay networking so that each container has its own IP address. This can mean either via VXLAN as can be found on Joyent's Triton, Docker Swarm w/ the overlay driver, Cisco's Mantl, a project like Weave or Calico, etc. While you can do single-host testing with the out-of-the-box Docker bridge driver, as you've discovered that won't work once you are in a multiple host environment.
