### ISSUE TITLE
onEvent hook

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#227]
There are a number of cases where we've seen folks want something to happen "after the application starts" (ref #204 #210 #196) and this has caused confusion where they try to pack the application into the `preStart` handler as a result.

One of the reasons why we don't have a "run immediately" option for tasks is that when we fork for the main process it takes a non-zero (and for some applications like Java apps a _long_ time) for the application to be ready. Which is fine for health checks, possibly complex to handle for tasks.

This proposal is to have a hook similar to `preStart`, `preStop`, and `postStop` in that it runs once only, and is fired when the application first passes a health check.

Complications / questions:
- I've been concerned (based on experience seeing misconfigurations) that we've increased the configuration surface so much that it's becoming harder to use.  Every new feature expands this surface area and adds new possibilities for user confusion, so every new feature needs to justify itself that much more.
- Should a ContainerPilot configuration have the ability to have more than one `onHealthy` hook (i.e. it's associated with the service and not the entire config)?
- What happens with an `onHealthy` hook when we SIGHUP ContainerPilot?

**Comment by tgross** [comment]
cc @jasonpincin @jacobloveless, who were originators of this proposal

**Comment by jacobloveless** [comment]
To me this is really a `postStart` hook. E.g. after the app has started. Increasing the surface area here seems ok as the hooks are optional - whereas a synthetic minimum number of hooks leads to abusing things like onHealth with `if(ran already once;then do nothing)`

**Comment by tgross** [comment]
> To me this is really a postStart hook. E.g. after the app has started.

The reason I'd shy away from that name is that we need it to be tied to health checks in order to be useful. If it's merely "after we start the application" then I'm afraid of getting a lot of buggy hooks that assume the application is not just forked but is ready to do work.

> Increasing the surface area here seems ok as the hooks are optional - whereas a synthetic minimum number of hooks leads to abusing things like onHealth with if(ran already once;then do nothing)

Yah we totally do that in a bunch of the github.com/autopilotpattern examples. 😊

**Comment by jacobloveless** [comment]
What about the situation in which you cannot pass a health check until
you’ve started the app and - say - updated a config from consul ?


On October 4, 2016 at 10:49:53 AM, Tim Gross (notifications@github.com)
wrote:

To me this is really a postStart hook. E.g. after the app has started.

The reason I'd shy away from that name is that we need it to be tied to
health checks in order to be useful. If it's merely "after we start the
application" then I'm afraid of getting a lot of buggy hooks that assume
the application is not just forked but is ready to do work.

Increasing the surface area here seems ok as the hooks are optional -
whereas a synthetic minimum number of hooks leads to abusing things like
onHealth with if(ran already once;then do nothing)

Yah we totally do that in a bunch of the github.com/autopilotpattern
examples. 😊

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joyent/containerpilot/issues/227#issuecomment-251410907>,
or mute the thread

**Comment by jasonpincin** [comment]
Completely on-board with wanting to minimize surface area, but in this case I believe increasing the surface area will reduce confusion rather than increase. It seems very confusing, to me at least, that "one time when app loads" stuff may be found in `preStart`, or in a health check script, or in a task that somehow kills itself after running once... all of these seem like confusing work-arounds. Having some sort of "when ready" hook would be much more clear.

I like the `postStart` name because it's consistent, however, since the hook would be tied to a health check, and each service can have it's own health check I believe we must offer this hook on a per-service basis rather than configuration wide, and thus the `postStart` (which is semantically consistent with the other configuration-wide hooks) could be the wrong name. 

To think about this further... if you wanted to make the hook config wide, what would trigger it? The first health check? Once all services were healthy? I'd lean toward "all services healthy" being the least confusing there, but this would fail to address some needs - such as when one service depends on another to become healthy. I can offer a more concrete example if needed.

**Comment by jasonpincin** [comment]
Another possibility is to have a config wide hook that runs repeatedly (like a health check) after the primary processes is spawned, UNTIL it returns exit code 0. Then it stops. Could define more meaningful exit codes: 0 = Ready, 1 = Error, 10 = Not Ready, 20 = Still working, etc.

**Comment by geek** [comment]
`onHealthy` -> sounds like an event that will run more than once, whenever the application becomes healthy again. Possibly rename to `onceHealthy`, but I still prefer `postStart` - the application started successfully.

**Comment by jasonpincin** [comment]
The more I think about it, the more I like the idea of one `postStart` hook that respects exit code `75` which causes ContainerPilot to retry the `postStart` script after a documented (short) period of time. This keeps it in line with the other hooks in the config file, and provides the needed flexibility without the ceremony of multiple interface `onHealthy` scripts, etc. The `postStart` script could do whatever checks it needs to do to insure it's able to do it’s job, and exit with code `75` if conditions are not where they need to be; for example: a slow to start application isn’t yet responsive.

**Comment by tgross** [comment]
The `postStart` you're proposing [here](https://github.com/joyent/containerpilot/issues/227#issuecomment-251972270) is just another health check but one that stops after one use. In most use cases that we've seen, the end-user would end up having to reimplement everything they do in the health check again (or at least call it). Except now they have to combine all the health checks into a single call and can't have separate behaviors for separate container services that we're advertising. What does this proposal add over having the end user add the behavior to their own health checks?

> exit code 75

Why 75? I might be missing something about the significance of that code.

**Comment by jasonpincin** [comment]
>>> Why 75? I might be missing something about the significance of that code.

http://www.unix.com/man-page/all/3/sysexits/

**Comment by jasonpincin** [comment]
> What does this proposal add over having the end user add the behavior to their own health checks?

Well, the more I thought about it, the more I though @geek was correct in his assertion that `onHealthy` (and potentially `onUnhealthy`) should run every time those events occurred. I'm thinking of use cases where we need to do something to respond to a health check failing, or passing again after failing (basically any time the status changes). However, that makes them not ideal for doing something once after start as we're discussing here.

I think you're right, that all of these things are closely related. You could put `onHealthy` and `onUnhealthy` logic into the health check. And you can put `postStart` into the healthCheck too (although in some situations you need to ask which health check? Could be dependency problems). And this will absolutely work (for the most part), but the two issues I see are:

1. The health check script(s) get larger and more complicated which may not be a great thing for something running very frequently.
2. It's potentially confusing. Someone looking and saying, this is supposed to be a health check, why is it doing all these other (seemingly unrelated) things. 

So to answer your question on what I believe my proposal adds:
1. Clarity - The various tasks associated with bringing an app online and managing it's changing health is more clearly spelled out. 
2. Flexibility - Health Checks (and potentially `*Healthy` hooks operate on a per-service basis while `postStart` is a per-app basis. Maybe I want to do my "after start" activities after one service is healthy, or after all three are healthy, or after something completely unrelated to a health check (a consul event for example)... this combination of hooks, IMHO, gives me a way to define those various requirements clearly.

YMMV. Admittedly, I've not seen a lot of concrete use cases yet, so this is a lot of conjecture.

**Comment by justenwalker** [comment]
How about something more extensible like `onEvent` which calls the command with an argument about the event type.

```json
{
    "onEvent": [
        "/bin/handle-event.sh",
        "${eventType}",
        "anotherArg"
    ]
}
```

Or perhaps, by convention, the first argument is the event type or something.

**Comment by tgross** [comment]
Combining the above with some sidebar discussion, the changes proposed in https://github.com/joyent/containerpilot/issues/245, and the changes proposed in https://github.com/joyent/containerpilot/issues/236, we can come around to the following config syntax:

```
health {
    Service = "app"
    check = "/usr/bin/curl --fail -s -o /dev/null http://localhost/app"
    poll = 5
    timeout = "5s"
    onEvent {
        condition = "firstFail"
        command = "/usr/local/bin/do-on-first-fail"
    }
}
```

For conditions I'd propose we have:
- firstPass: first time we pass
- firstFail: first time we fail
- becomesHealthy: changes from unhealthy to healthy
- becomesUnhealthy: changes from healthy to unhealthy
- exitCode: on a particular exit code

**Comment by tgross** [comment]
Given pushing #236 off, the config will instead be as follows:

```json
services: [
  {
    "name":  "app",
    "check": "/usr/bin/curl --fail -s -o /dev/null http://localhost/app",
    "poll": 5,
    "ttl": 10,
    "timeout": "5s",
    "onEvent": {
        "condition": "firstFail",
        "command": "/usr/local/bin/do-on-first-fail"
    }
}
```

This also makes this a 2.x-compatible enhancement.

**Comment by tgross** [comment]
We'll be handling this via the work in the [RFD](https://github.com/joyent/rfd/pull/13), in particular the events described under [multiprocess dependency management](https://github.com/joyent/rfd/blob/4b6c69b42cf6833f177826d9a30e14c6ad5cb42c/rfd/0086/multiprocess.md#dependency-management)

**Comment by tgross** [comment]
Partially released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.1. I'm going to close this issue in lieu of further design discussion in [RFD86](https://github.com/joyent/rfd/blob/master/rfd/0086/README.md) or by opening new issues.
