### ISSUE TITLE
proposal: make service registration optional

### ISSUE THREAD

**Issue by bsphere** [joyent/containerpilot#237]
[nomadproject.io](http://nomadproject.io) registers services in consul,
in order to use containerpilot either nomad or containerpilot should have the option to skip registering the service..
[registrator](https://github.com/gliderlabs/registrator) has this option (with labels or env vars) and I suggest to have something similar in the service definition of containerpilot based on an ENV var, so when running a container through nomad, containerpilot won't register the service (but will, in other scenarios).

**Comment by justenwalker** [comment]
The service section is optional. If you leave it out, then it won't
register with consul. Does that work in this case?

**Comment by fitz123** [comment]
@justenwalker I don't think this is the case. The proposal is about automatically detection: do we need to register service into the consul or we don't depends on ENV variables.
It'll make possibly to use same containers into 2 environments: let's say on its own or via Nomad. Nomad gonna add special env variable which disables CP service registration.

@bsphere One thing I cannot get: does something brake if you have 2 systems which register the same service with the same service-ID? Just wonder if you can adjust all parameters to have the similar service definitions. In this case issue will be _kind of_ solved, if I got everything right)

**Comment by justenwalker** [comment]
You can also golang template the container pilot config which supports env
variables. You can use that to selectively add the service section if an
env variable exists.

On Sun, Oct 30, 2016, 11:04 AM Anton Lugovoi <notifications@github.com>
wrote:

@justenwalker <https://github.com/justenwalker> I don't think this is the
case. The proposal is about automatically detection: do we need to register
service into the consul or we don't depends on ENV variables.
It'll make possibly to use same containers into 2 environments: let's say
on its own or via Nomad. Nomad gonna add special env variable which
disables CP service registration.

@bsphere <https://github.com/bsphere> One thing I cannot get: does
something brake if you have 2 systems which register the same service with
the same service-ID? Just wonder if you can adjust all parameters to have
the similar service definitions. In this case issue will be *kind of*
solved, if I got everything right)

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/joyent/containerpilot/issues/237#issuecomment-257156489>,
or mute the thread

**Comment by fitz123** [comment]
That's something interesting even for me. I didn't know (and didn't try ether) that it's possibly to use go template language in there. So basically you mean that something like this should work:
```
...
  {{if .SERVICES_ON}}"services": [
    { "name": "service0" },
    { "name": "service1" }
  ],{{end}}
...
```

**Comment by justenwalker** [comment]
Yeah that should work

**Comment by bsphere** [comment]
I didn't think of this as well... seems like it can achieve exactly what I asked for.

@fitz123 I don't believe you have any control over the service id from Nomad

**Comment by tgross** [comment]
I think @justenwalker has got a good path forward here.

See also https://github.com/joyent/containerpilot/issues/193 for a proposal around user-configrable service identifiers and https://github.com/joyent/containerpilot/issues/117 for registering services without ports.

**Comment by tgross** [comment]
Because we've already got issues open to cover the issues here and we've got a decent work-around, I'm going to close this issue.
