### ISSUE TITLE
consul agent discovery backend

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#246]
A common case for all deployments of ContainerPilot on container-native environments like Triton (or a PaaS) is having an instance of Consul running as an agent co-process inside the container. In fact, this is why we created the co-process feature in the first place. All autopilotpattern example blueprints include this. Instead of relying on end-users to hack this in themselves, we're going to provide the option on the Consul discovery backend to run Consul as a coprocess with a known-good configuration. The ContainerPilot configuration to launch this looks like the following:

```
consul {
    host = consul.example.com:8500
    agent = true
    retry-interval = 10s
}
```

(Note this uses the new HCL config syntax from https://github.com/joyent/containerpilot/issues/236#issuecomment-261375257)

As part of this work, we'll add to our build packaging for ContainerPilot and a Consul agent in deb, rpm, apk, etc. formats.

**Comment by flyinprogrammer** [comment]
> build packaging for ContainerPilot and a Consul agent in deb, rpm, apk, etc. formats.
we already include the consul code base in CP, why not just have CP also be a consul agent?

**Comment by fitz123** [comment]
I bet no one wants to handle updating process to match new consul releases, that's just too much of additional headache, comparing to using separate, independent package

**Comment by tgross** [comment]
> we already include the consul code base in ContainerPilot, why not just have ContainerPilot also be a consul agent?

I definitely considered embedding Consul in ContainerPilot (although realistically it would be tacking on ContainerPilot onto Consul rather than the other way around). But @fitz123 has it: this way we avoid any risks around sharing memory with Consul, we can drop-in new versions of Consul w/o code changes, we're not screwing around with Consul code base and risk losing their interest in supporting such a crazy use case, etc., etc.

**Comment by tgross** [comment]
Moving this down into 2.x

**Comment by tgross** [comment]
As I'm hacking into this I'm discovering that we could really use one more layer of indirection in the config parsing. Right now we instantiate all the [`App`](https://github.com/joyent/containerpilot/blob/d93c156efa93cce7f0a82ec9cb4c2baa8b7a10ce/core/app.go#L31-L50) collection fields -- `Services` (and associated `DiscoveryBackend`), `Backend`, `Tasks`, `Coprocess`, and `Telemetry.[]Sensor` -- by passing the raw interface we get from `mapstructure` into the associated subpackage's `NewX` function.

If instead we parsed the `mapstructure` instances in the `config` package and passed only a parameters struct into the `NewX` function, we'd fully decouple all the parsing of the configuration from the behavior. This will make it a lot easier for a chunk of the discovery config to create a coprocess as we need in this issue.

**Comment by tgross** [comment]
Realized this morning that it turns out the config parsing is a bit of a red herring... the Consul Agent can't act as just another co-process because the co-processes are started with the other pollables, which would mean the `preStart` wouldn't have access to the agent. Instead we need to fork the agent before `preStart`, and probably wait for it to join the Consul cluster too.

**Comment by tgross** [comment]
A few other interesting edge cases here:

- Some users will most likely want to configure the agent based on something in the `preStart` and those users will still need to use a `coprocess` instead of the agent. This feature is only helpful for users who don't want to configure it in the `preStart`.
- On configuration reload we stop and reload co-processes. We should probably stop the agent as well.

This is leading me to think that we should probably have an `agent` subpackage that manages the agent. We could potentially use this to do etcd agents as well if someone feels like implementing them and assuming we don't [drop etcd support](https://github.com/joyent/containerpilot/issues/251).

**Comment by BobDickinson** [comment]
I'm definitely in agreement with having reliable access to consul via consul agent in preStart.  I've seen both hacks around this in projects I've been working with (moving preStart logic to an onStart process wrapper script, and cheating by talking directly to the main consul server in preStart).  Those are both pretty ugly.

**Comment by misterbisson** [comment]
> I've seen both hacks...pretty ugly

Like you, I'll do just about anything to avoid wrapping shell script around my main process, but talking directly to the cluster of Consul servers (not agents) in preStart isn't really a hack or morally wrong.

Here's the thing: The agent matters when registering an instance of a service and reporting its health but far less so for reading the catalog. 

Because agents don't participate in Consul's consensus raft, they have to query one of the raft servers to get a consistent, non-stale read from the catalog ([though you may have configured it differently](https://www.consul.io/docs/agent/http.html#consistency-modes)). So, you can query the agent, then the agent queries the cluster, or you can query the cluster directly.

That's my defense for the validity of my suggestion in https://github.com/joyent/containerpilot/issues/273#issuecomment-275262056, anyway. 

I still think there's a better answer, but there isn't one that's going to result in more correct results, or faster queries, or more efficient performance.

**Comment by BobDickinson** [comment]
> I've seen both hacks...pretty ugly

OK, I shouldn't have used the "H" word.  Or the "U" word either I guess.  No offense intended.

I'm am far from confident in my knowledge of the inner workings of consul.  But I have been moving away from just using the single consul instance at "consul", and instead using consul agent and multiple consul servers following the patterns I've seen in the various Autopilot projects. 

My assumption was that using consul agent would be more reliable than just doing a curl ${CONSUL}.  My thinking was that consul agent would be smarter about finding a working raft member if, say, one of the members had failed, but was not yet removed from CNS, and was still somehow connectable (not that that's a very likely scenario, but curl is certainly not going to figure that out).  That's a pretty low probability edge case, if it's even possible, and the failure is low impact (the service fails to start, but trying again succeeds).

Anyway, that was the basis of my newfound preference for using consul agent instead of just connecting to consul directly.

**Comment by tgross** [comment]
We're not going to go ahead with this per https://github.com/joyent/rfd/pull/13. We'll support Consul only, but the new first-class multiprocess support will make the scenario described here much easier to configure.
