### ISSUE TITLE
Type signal for coprocesses 

### ISSUE THREAD

**Issue by ev4ern** [joyent/containerpilot#269]
Type signal for coprocesses on contailnerpilot sighup

**Comment by ev4ern** [comment]
nginx workers stay on kill

![nginx](https://cloud.githubusercontent.com/assets/15714617/22046430/9c309bf0-dd31-11e6-86f4-6155d8625095.png)

need gracefully reload

It may be something like 
```
  "coprocesses": [
    {
      "name": "nginx",
      "command": [
        "nginx", "-g", "daemon off;"        
      ],
      "restarts": "unlimited"],
      "signal": "SIGHUP"
    }],
  ]
```
to override default behavior

**Comment by tgross** [comment]
Currently when ContainerPilot receives SIGHUP it stops (SIGTERMs) the co-processes because the ContainerPilot configuration may have changed, which includes whether or not the co-process exists at all or what its command is.

I'm not sure I completely understand what you're asking for here, but are you proposing that we allow the co-processes to be "stopped" via SIGHUP instead? How would we handle changes to the co-process configuration in that case?

**Comment by ev4ern** [comment]
> configuration may have changed

You are right!
