### ISSUE TITLE
In a multi nodes consul cluster, sometime the critical service cannot be recovered after registering the same service

### ISSUE THREAD

**Issue by lmgnid** [joyent/containerpilot#277]
In our consul + container pilot setup, we found this issue bellow:

- Consul is a 3 nodes cluster setup, we are using CNS in the container pilot config files

- For Consul agent setup, we are using the default "consul agent-less" method but NOT the "co-process" consul agent client, in another word, our services will be registered as one of the Consul 3 nodes

- Sometime, when the service has a healcheck failed once for whatever reasons, this service will be marked as Critical with node IP as for example Consul server 2. Like this one bellow:
4058f869db2a 192.168.0.12 1 failing
Serf Health Status serfHealth passing
svc-5bcd5ba35387 svc-5bcd5ba35387 critical

- When the healcheck is recovered, as we are using CNS+ 3 Consul cluster servers, the same service maybe registered with node IP as for example Consul server 3.
07affbd0a384 192.168.0.7 2 passing
Serf Health Status serfHealth passing
svc-5bcd5ba35387 svc-5bcd5ba35387 passing

- It seems the Consul cluster will not mark the previous critical service as health, even they are the same service "svc-5bcd5ba35387"

I am not sure if this should be a bug, but it seems lots of people will have this issue when using multi nodes  Consul cluster + Container Pilot, any suggestions will be great, or will the "co-process + consul agent client" solve this issue? Thanks!

**Comment by misterbisson** [comment]
We could definitely make it more clear, but you _must_ run Consul as a co-process if you're using ContainerPilot with a multi-node Consul cluster. If not, the result is exactly what you described.

Your choices to resolve this are:

1. Run a single node Consul cluster. If you're just using Consul for discovery, then it's not actually storing any persistent data. If your Consul node fails, start another. Even if it has no data, everything _should_ be recovered. However, k/v data and locks won't be, so that might cause problems.
2. Run Consul as a co-process in your container so that you can use the Consul agent.

Number 2 is the recommended general solution, but 1 works great in many circumstances.

**Comment by lmgnid** [comment]
Thanks and we will try the co-process Consul agent.
