### ISSUE TITLE
Support Consul Multi DC

### ISSUE THREAD

**Issue by lmgnid** [joyent/containerpilot#288]
Is there any way to have Container Pilot to register its service  or check backend service in another Consul DC over "WAN"?

For example, in "services" part, can it register itself in another "dc2"?
  "services": [
    {
      "name": "service1@dc2",
      "port": 80,
      "health": true,
      "poll": 10,
      "ttl": 25
    }
  ]

Or in "backends" part, can it check the health in another DC "dc2"?
  "backends": [
    {
      "name": "service2@dc2",
      "poll": 30,
      "onChange": "/onchange.sh"
    }
  ]

**Comment by tgross** [comment]
We originally didn't provide a native way to do this because we had support for etcd which wasn't data center aware. But in v3 we've cut etcd support which means we can revisit this idea.

It looks like the Consul API supports DC-specific queries for health checks via the `?dc=` query parameter (ref https://www.consul.io/docs/agent/http/health.html#health_service). The Consul API doesn't support having the service explicitly register for a particular DC -- it's already handled for you by registering with particular agents. So this should be pretty easy to add.

In the meantime you can workaround this by passing the DC as an environment value and interpolating that into the health check name. I do this a lot in our integration tests for autopilotpattern examples.

So for example you might run your container with `docker run -e TRITON_DC=us-east-1 mycontainer /bin/containerpilot myapp` and then your ContainerPilot config looks like:

```json
{
  "services": [
    {
      "name": "myapp-{{ .TRITON_DC }}",
      "port": 80
    }
  ]
}
```

**Comment by tgross** [comment]
I've updated the issue title here and have marked it as an enhancement for v3. If you're interested in contributing a PR for it, the relevant sections would be adding `DC` as a field to the [`Backend` struct](https://github.com/joyent/containerpilot/blob/master/backends/backends.go) and then add that field to the [`CheckForUpstreamChanges` function](https://github.com/joyent/containerpilot/blob/99261a02ef12e116cda7d9bd27b6cd35e8d8b630/discovery/consul/consul.go#L177)

**Comment by tgross** [comment]
Going to snag this as part of a batch of post-v3 Consul-related improvements.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/400 for this.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.1.0
