### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by sourcec0de** [joyent/containerpilot#293]
**For Reference**

If anyone gets this error 

```
2017/03/09 08:42:53 fork/exec /etc/lifecycle/preStart: exec format error
```

when using the lifecycle hooks like `preStart`

the solution is to add `#!/bin/sh`

**Comment by tgross** [comment]
Thanks for the report @sourcec0de. That particular error is bubbling up from the underlying OS: an executable file that isn't in ELF format needs to have _some_ interpreter to run (`bash` or `sh` or even perhaps `/usr/bin/python`). You can get this same error like so:

```
$ touch test.sh
$ chmod +x test.sh
$ ./test.sh
zsh: exec format error: ./test.sh
```

Note that your shell may do some guesswork here and try to run an executable file anyways (in zsh if I do `echo true > test.sh` instead of just giving it a blank file it works). But we can't really emulate that behavior in ContainerPilot because we don't know much about what shell might be available to us.
