### ISSUE TITLE
Backends bug?

### ISSUE THREAD

**Issue by yellowmegaman** [joyent/containerpilot#301]
If backends stanza is to survive 3.0 version.

From the docs:
```backend service that this container depends on```

I'd like to ask why containerpilot is not waiting for them to go online before starting application. Is it a bug or intended behavior?

**Comment by tgross** [comment]
The v2 design is intentional, because we don't want to force an application to wait if it doesn't have to. For example (and this is a real use case from a large retailer we know of), we could have an Nginx that we're happy to have serve static assets but report a HTTP503 on the app server location block when there are no upstream app servers available (see the example Nginx config below). We expect that the `onChange` behavior is what handles this.

```
{{ if service "app" }}
upstream backend {
    {{ range service "app" }}
    server {{ .Address }}:{{ .Port }};
    {{ end }}
}{{ end }}

location / {
    root /srv;
}

location /app {
    {{ if service "app" }}
    proxy_pass app;
    {{ else }}
    return 503;{{ end }}
}
```


In v3 this is changing a bit, largely because there are (as you've noted) some applications that can't handle this gracefully. The `depends on` blocks described in [RFD36 `config.md`](https://github.com/joyent/rfd/blob/master/rfd/0086/config.md) allow you to explicitly define behaviors like waiting for another service to become healthy.

**Comment by yellowmegaman** [comment]
Thanks for clarification! Can't wait for 3.x stable ;)
