### ISSUE TITLE
control: Input for PutEnv API endpoint

### ISSUE THREAD

**Issue by cheapRoc** [joyent/containerpilot#336]
Ref: `PutEnv POST /v3/environ` within [joyent/rfd#86](https://github.com/joyent/rfd/blob/master/rfd/0086/mariposa.md#putenv-post-v3env)

Just want to clearly define the implementation before moving ahead/finalizing...

- `'{"ENV1": "value1", "ENV2": "value2", "ENV_TO_CLEAR": ""}'` Makes sense, "clearing" the environment variable with an empty string.

- `'{"ENV1": "value1", "ENV2": "value2", "ENV_TO_CLEAR": "null"}'` from the RFD this sounds as if its supposed to clear as well?

- `'{"ENV1": "value1", "ENV2": "value2", "ENV_TO_CLEAR": null}'` Same question, is the expectation that this will be input?

- `'{"ENV1": "value1", "ENV2": "value2"}'` does not touch `"ENV_TO_CLEAR"` set by previous requests.

Also, I believe I'm just going to iterate over the input map and `os.Setenv`.

**Comment by tgross** [comment]
All that looks good, except perhaps:

> '{"ENV1": "value1", "ENV2": "value2", "ENV_TO_CLEAR": "null"}'

This one is problematic, because it's a string `"null"` and not the JSON value `null`. I don't think we should support this in the interest of principle-of-least surprise. But supporting a real JSON `null` should clear the value.

Effectively what we end up with is matching the behavior of the shell.

- `"ENV_TO_CLEAR"=null` is the equivalent of `unset ENV_TO_CLEAR`
- `"ENV_TO_CLEAR"=""` is the equivalent of `ENV_TO_CLEAR=`
- `"ENV_TO_CLEAR"="null"` is the equivalent of `ENV_TO_CLEAR=null`, which is a legal string in the shell. (Although probably not an awesome idea to do!)

**Comment by cheapRoc** [comment]
Thanks, I'll pass the `"null"` through since that's how the shell behaves.

**Comment by cheapRoc** [comment]
Ref: #329

**Comment by cheapRoc** [comment]
This issue can be safely closed once PR #329 is accepted.

**Comment by tgross** [comment]
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.3
