### ISSUE TITLE
define which ip to register in consul

### ISSUE THREAD

**Issue by yellowmegaman** [joyent/containerpilot#350]
Hi there!

Let's suppose i've got docker container with service port mapped to host.
With default configuration docker ip is registered in consul, but it's not reachable from other hosts.

Example:
host: 192.168.102.67
docker container ip: 172.17.0.2
port 5432
consul service registered with 172.17.0.2 5432

so any way to specify 192.168.102.67?

Thanks a lot in advance!

**Comment by tgross** [comment]
> With default configuration docker ip is registered in consul, but it's not reachable from other hosts.

Having overlay networking of some kind in play (or host networking) has always been an intentional requirement for use of ContainerPilot and the Autopilot Pattern. The reason is simple -- the container doesn't _know_ what the NAT'd IP address is so there's no way for it to specify what that IP address might be. You'd need some external mechanism to specify the IP address for every container, and we're intentionally avoiding having a dependency on these kinds of external mechanisms.

Just as a word of advice, using NAT is also the worst performing of all the various networking options.

I'd highly recommend using either an overlay network (ex. VXLAN) or host networking. If you're worried about port conflicts with host networking, then you can use whatever mechanism you're using to schedule workloads to provide the application with a port number it should be using as an environment variable.

**Comment by tgross** [comment]
I'll also point out, although it doesn't solve your particular problem with NAT, that there's already an `interfaces` field that one can use to tell ContainerPilot which IP to advertise among the interfaces it can see.

**Comment by yellowmegaman** [comment]
Thanks for the info! Actually i we've been using containerpilot a lot  with consul and etcd+flannel for networking, but etcd is pain, sooner or later. Also almost all overlay networks don't handle partial connectivity loss well, so we've decided to drop it and go full net=host mode. 
But there's blue-green/canary update strategy that could play just nice with Hashicorp Nomad dynamic ports, without added complexity - that's where we'd like to register host ip instead of container's.

**Comment by tgross** [comment]
As far as I know nothing in Nomad's dynamic ports setup precludes using host networking, but you'd probably want to check with the folks at Hashi on that.

**Comment by tgross** [comment]
I'm going to close this issue. We're not planning on supporting NAT because it ties us to particular external implementations.

**Comment by yellowmegaman** [comment]
Well, you've been much help, great many thanks!

**Comment by ahelal** [comment]
@tgross I agree that all the arguments put forward make sense, But it is really almost impossible to implement in the following condition. 
ECS currently supports bridge and host. Now host might seem a good choice as you mentioned, but in a case where we package HAProxy with each Container to do load balancing juggling ports is full time job and not really realistic .

The suggestion here is to make an explicit option to override the advertise IP regardless of the the underlying network implementation.

**Comment by tgross** [comment]
@ahelal it's not that I don't understand the problem, it's that a solution for NAT is intentionally out of scope for ContainerPilot. You can already override the IP via the `static` value in the `interfaces` config (see the last bullet point in https://github.com/joyent/containerpilot/blob/master/docs/30-configuration/32-configuration-file.md#interfaces). Anything beyond that, I would recommend finding a different solution than ContainerPilot.

**Comment by ahelal** [comment]
@tgross Ohh sorry did not see that 👍 damn my lazy eye
