### ISSUE TITLE
more template functions

### ISSUE THREAD

**Issue by ahelal** [joyent/containerpilot#370]
Hey, 

Thank you for container pilot. I would like to make a PR to give a little bit more power to the go templating, but would first want to get some feedback.

I want the backend to be dynamic. We use client side load balancing. Each container is packaged with HAProxy in our base image. And I want the images based on our base image, can configure the background vie environments. It is really hard to achieve that with limited template functionality.

For example exposing [env](https://github.com/hashicorp/consul-template/blob/8494b8b81df7c03a0503e08814e7ce24c576ee25/template/template.go#L217)  or [loop](https://github.com/hashicorp/consul-template/blob/8494b8b81df7c03a0503e08814e7ce24c576ee25/template/template.go#L221) like consul-template or others

Regards

**Comment by tgross** [comment]
Can you provide an example of what this would look like?

**Comment by ahelal** [comment]
@tgross thank you for your reply. 

docker file example
```
from XXXXXXX
ENV  SERVICE_NAME_1="pilot_redis"
ENV  SERVICE_PORT_1=6379
ENV  SERVICE_NAME_2="pilot_mysql"
ENV  SERVICE_PORT_2=3306
COPY ./app.py /app.py
CMD [ "/bin/containerpilot", "-config", "file://etc/containerpilot.json","/app.py"]
```

sample container.json
```
  "backends": [
    {{ range $i := loop 0 30 -}}{{ if (env (printf "SERVICE_NAME_%d" $i)) }}
    {
      "name": "{{ env (printf "SERVICE_NAME_%d" $i) }}",
      "onChange": "/bin/on_change.sh"
    },
    {{- end }}{{- end }}
```
Probably a might be a better way or a custom function that can solve this better.

**Comment by tgross** [comment]
My main filters for adding new features and configuration complexity are that the added complexity is both necessary to the problem and isolated (opt-in). This feature seems to pass those filters; you can't dynamically add backends via environment otherwise and the functions don't exist to someone who doesn't use them. Matching what `consul-template` does is a nice touch too.

Note that you're showing v2 configuration here, and this feature can only go into v3 (the `master` branch). We're not adding any new features to v2 (the `v2_backports` branch).

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-RC1
