### ISSUE TITLE
Consul services left on docker kill or container crash

### ISSUE THREAD

**Issue by rickardrosen** [joyent/containerpilot#376]
I'm trying to get some clarity on how CP (2.7.3) will handle a SIGKILL signal, or what really happens when the wrapped application dies.

In our scenario we register the service with the hosts consul agent, i. e. we do not run consul agent as a co-process inside the container.
This mostly works great, unless containers are killed by something other than SIGINT.

This leads to a couple of issues and perhaps it's just down to configuration or ignorance on my part:

1. On "docker kill" I have found no way to have CP de-register the service before the container is teared down. I have experimented with the different timeouts to no avail.
The docs however state: 
> If -1 is given for stopTimeout, ContainerPilot will kill the application immediately with SIGKILL, but it will still deregister the services.

Which leads me to believe there is a way to de-register on KILL. Is that assumption correct?

I have however not found a way for the container to de-register, which has required me to install a pre-start script that removes and dangling services on container start.

2. When running nginx in a container wrapped by CP, it will leave a dangling service on **clean** shutdown as well, probably due to some issues with different signals (nginx wants a TERM or INT).

3. If, for example, a wrapped node application dies, CP will leave the service dangling until "deregisterafter" times out at which point the service will be removed.

What could be the cause of what I'm seeing and is it to be expected?

**Comment by tgross** [comment]
> On "docker kill" I have found no way to have CP de-register the service before the container is teared down. I have experimented with the different timeouts to no avail.
...
> Which leads me to believe there is a way to de-register on KILL. Is that assumption correct?

It is not possible for ContainerPilot to deregister on SIGKILL, as SIGKILL cannot be caught or ignored by a process (IIRC this is a POSIX standard). [`docker kill`](https://docs.docker.com/engine/reference/commandline/kill/) sends SIGKILL, so we can't do anything about that.

The default behavior of [`docker stop`](https://docs.docker.com/engine/reference/commandline/stop/) is to send SIGTERM, waits 10 seconds, and then send SIGKILL. You should see the behavior described in the documentation in that case, assuming that all the cleanup is finished by the time Docker's timeout expires.

When ContainerPilot (in v2) receives SIGTERM, it stops all pollables, [deregisters all services](https://github.com/joyent/containerpilot/blob/3372754eec6805b0d6c417b96404526ceff7849d/core/app.go#L236), runs the `preStop` handler, and then sends it's own SIGTERM to the shimmed application. The `stopTimeout` [starts running](https://github.com/joyent/containerpilot/blob/3372754eec6805b0d6c417b96404526ceff7849d/core/app.go#L247) after we've sent the SIGTERM. Only after the `stopTimeout` runs out will ContainerPilot give up and send a SIGKILL to the child process. So the bit you're reading there in the docs is about ContainerPilot send a SIGKILL, not handling SIGKILL from the Docker daemon.

Also, what ContainerPilot's `stopTimeout` can't do anything about is the Docker daemon getting tired of waiting around for it to clean up after SIGTERM. After the Docker daemon hits its own timeout, it'll send SIGKILL and we die immediately whether we've deregistered and gracefully stopped or not. So if the time it takes for ContainerPilot to run the `preStop` and do all the cleanup work exceeds the Docker daemon's timeout, then we might not get a chance to cleanup properly.

---

Somewhat unrelated:

All that being said, now that I'm taking a second look at this area of the code base, I see that we should probably swap [this line](https://github.com/joyent/containerpilot/blob/3372754eec6805b0d6c417b96404526ceff7849d/core/app.go#L236) and [this line](https://github.com/joyent/containerpilot/blob/3372754eec6805b0d6c417b96404526ceff7849d/core/app.go#L235) so that folks who are using a Consul agent co-process don't end up with a race between shutdown and deregistration. But as you said, you're not using a co-process so you won't be affected by that bug.

**Comment by benjamin-bergia** [comment]
Same issue here but I am using a consul agent as a coprocess and it does fail to deregister some nodes. Would be great to have a fix for this.

**Comment by rickardrosen** [comment]
Got a bit better undestanding now, thanks for the explanation Tim!

I have worked around the problematic scenarios by de-registering "stale"
services with a prestart script and an aggressive deregistertimeout.

/Rickard
