### ISSUE TITLE
Emit RFC3339/ISO8601 dates

### ISSUE THREAD

**Issue by mterron** [joyent/containerpilot#422]
From observation, Containerpilot seem to be using UTC time for it's log (please correct me if I'm wrong).
Currently Containerpilot emits dates on the following format:
YYYY/MM/DD hh:mm:ss

Instead, it should output its log dates in a std format like [RFC3339](https://www.rfc-editor.org/rfc/rfc3339.txt)

**Comment by tgross** [comment]
We're currently emitting the default configuration of the [formatters](https://github.com/sirupsen/logrus#formatters) provided with Logrus. Digging into the Logrus code this suggests we should be getting [`RFC3339`](https://github.com/sirupsen/logrus/blob/7dd06bf38e1e13df288d471a57d5adbac106be9e/formatter.go#L5) by default, but maybe this was changed in a newer version of Logrus. I'll have to look into it.

Arguably we might want to [pass options](https://godoc.org/github.com/sirupsen/logrus#TextFormatter) to the formatter structs so as to format them in a particular way determined by the user, and just have a sane default.

**Comment by tgross** [comment]
I dug into this a bit more and the output varies depending on the log formatter chosen:

- `default` uses the golang stdlib logger and the `LstdFlags` format. The stdlib doesn't give us the option of a RFC3339 format as far as I can tell.
- `json` uses the RFC3339 format w/ TZ: `{"level":"debug","msg":"app1.kill","time":"2017-07-03T13:18:04-04:00"}`
- `text` uses logrus Text format, which is frankly a little weird:
  - If there's a TTY attached, we get messages like `DEBU[0006] app1.kill`, where "0006" is the _number of seconds elapsed since start_. (Wtf?)
  - If there's no TTY attached, we get a format like the following: `time="2017-07-03T17:26:00Z" level=debug msg=app1.kill`

So the only case where we're not getting the RFC3339 format is in the stdlib log format. Unless you know of a way to coerce the stdlib log format to do otherwise, it's my recommendation to use the `text` format or `json` format. These are also structured formats which are better for log ingest.

**Comment by mterron** [comment]
This snippet emits rfc3339 dates using the std log lib.
https://play.golang.org/p/RC9JxV_LaA
Can you take a look Tim?

**Comment by tgross** [comment]
Seems sane as far as the timestamp goes, but how do we get the level block in there? I'm definitely open a PR on this.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.2.0
