### ISSUE TITLE
Interval jobs not firing

### ISSUE THREAD

**Issue by jhmartin** [joyent/containerpilot#471]
I believe there is an issue with the documentation around periodic jobs.

The documentation states:
```
  {
      // this job will write metrics to our telemetry collector
      name: "sensor",
      exec: "/usr/local/bin/sensor.sh"
      when: {
        interval: "5s"
      }
    }
```

However, the output is:
```
time="2017-08-09T20:09:51Z" level=debug msg="interval expired but restart not permitted: sensor"
time="2017-08-09T20:09:51Z" level=debug msg="event: {Stopping sensor}"
time="2017-08-09T20:09:51Z" level=debug msg="event: {Stopped sensor}"
```
Adding a `restarts: "unlimited"` seems to resolve the issue.

```
Version: 3.3.3
GitHash: 8290ffa
```

**Comment by tgross** [comment]
@jhmartin I agree this is a gotcha. I'll see what we can do about clarifying the docs on this.

**Comment by tgross** [comment]
So the `bug` tag I added here is because of there's an obvious documentation bug. But I dug into this and my feeling is that this may actually be a misfeature.

For most use cases, an `interval` will also need the `restarts` field for the job to be set. The job will run its `exec` at the specified interval but only re-run it the number of times given by the `restarts` field. This allows a user to specify that a job is to run e.g. "every 5 seconds, at most 4 times" like so:

```json5
{
  name: "setup",
  exec: "/setup.sh",
  when: {
    interval: "5s",
  },
  restarts: 3 // setup will run a total of 4 times
}
```

I seem to recall during the v3 design discussions someone bringing up this use case, but at the moment I can't seem to dig up that discussion. I have the feeling it was a hypothetical feature rather than an end-user requested one.

As an alternative, maybe we could have the default behavior be the equivalent of `restarts: "unlimited"` whenever the `interval` field is set? This would be safely backwards compatible with anyone who's already setting `restarts: "unlimited"` for their `interval` jobs today. It _would_ break backwards compatibility for someone who was relying on the default `restarts: "never"` behavior for an `interval` job, but I have to believe that's such an extreme corner case as to be not something we need to worry about.

Marking this as a proposal for further discussion.

**Comment by misterbisson** [comment]
@tgross: good points and good proposal for resolution

**Comment by tgross** [comment]
I've opened https://github.com/joyent/containerpilot/pull/473 for review.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.4.0
