### ISSUE TITLE
[Question/Clarification] Consul Registration of Health Checks

### ISSUE THREAD

**Issue by vrenjith** [joyent/containerpilot#474]
We have been using `containerpilot` and this issue is to clarify our understanding of the way `containerpilot` registers the container as a service. As we see, the registration is done using the `catalog API` and not using the `agent API`. Is this by design or is it due to the way we have configured our services?
The sample `json` used by `containerpilot` is given below
```
{

    "consul": "{{NOMAD_IP_example}}:8500",
    "stopTimeout": 5,
    "services": [{
        "name": "example-service",
        "port": 8080,
        "health": "/usr/bin/curl --fail -s -o /dev/null http://localhost:8080/ping",
        "poll": 10,
        "ttl": 25,
        "interfaces": [
            "eth0"
        ]
    }]
}
```

Currently we see that unhealthy containers remain in consul. While, as per the documentation, if the health check happens at the `agent api`, then the default cleanup interval is one minute as per the docs for `DeregisterCriticalServiceAfter` at https://www.consul.io/api/agent/check.html. We were not seeing the behaviour and then started analysing the details.

**Comment by tgross** [comment]
> As we see, the registration is done using the catalog API and not using the agent API. Is this by design or is it due to the way we have configured our services?

We're using the [agent API](https://github.com/joyent/containerpilot/blob/c2e252522add379610915df4a5d9a4a9a463bfcb/discovery/consul/consul.go#L143), and I believe that's been the case for as long as I can remember. Which version of ContainerPilot are you using?

**Comment by tgross** [comment]
I think you're just missing a configuration option -- take a look at the v2 docs [here](https://github.com/joyent/containerpilot/blob/348b2544c8eb7a4edb234665a0cace0da6b0262e/documentation/12-configuration/README.md#services) and there's a `deregisterCriticalServiceAfter` field for services.

**Comment by vrenjith** [comment]
@tgross 
* That was a pretty fast response
* I think we are on a pretty old version `2.5.0`. Was the case anytime in containerpilot that the `catalog api` was being used?
* I observed this option`deregisterCriticalServiceAfter` in the job specification. Our current configuration files does not resemble the `v2` specification at all. We need to upgrade them I assume.
* I have a follow up question - Is this option `deregisterCriticalServiceAfter` will result in `consul` receiving the option `DeregisterCriticalServiceAfter` for the `check` registration?

**Comment by tgross** [comment]
> That was a pretty fast response

I try! 😀 

> I think we are on a pretty old version 2.5.0. Was the case anytime in containerpilot that the catalog api was being used?

I thought I remembered making that mistake at one point... but I just checked and it looks like even the [first commit](https://github.com/joyent/containerpilot/commit/aec016e13d87e01c5fa7080afd048bcb08179cf4) that includes the service registration was using the Agent API. That definitely includes version 2.5.0 which has [this code section](https://github.com/joyent/containerpilot/blob/08cbcc600facfcf7b1eb1879ffe8e9f2a5c4cac4/discovery/consul/consul.go#L127-L151). So that _should_ be using the Agent API. It's entirely possible that we broke that at one point and fixed it in a later release, or that client library had a bug at one point! Are you seeing requests in your Consul logs suggesting otherwise?

> Our current configuration files does not resemble the v2 specification at all. We need to upgrade them I assume.

The v2 configuration added features over time. So if you want to take advantage of the `deregisterCriticalServiceAfter` option and it wasn't available in the version you have, you'll need to upgrade. We don't really plan on supporting v2 for much longer though -- I'd recommend upgrading to v3 instead.

> Is this option `deregisterCriticalServiceAfter` will result in consul receiving the option `DeregisterCriticalServiceAfter` for the check registration?

Yes.

**Comment by vrenjith** [comment]
> Are you seeing requests in your Consul logs suggesting otherwise?
Yeah, I do see that the services are listed only when I query `v1/catalog/services`

> We don't really plan on supporting v2 for much longer though -- I'd recommend upgrading to v3 instead.
Okay, that's an important tip. Thank you. Let me check the v3 docs.

**Comment by tgross** [comment]
> Yeah, I do see that the services are listed only when I query v1/catalog/services

Well I was asking about Consul's own logs, and whether you see the PUT requests coming into to `/v1/agent/service/register`.

But if we're talking about queries -- are you making that query to the Consul agent on the same machine, or to the cluster? If you query the cluster (i.e. the servers) then you won't see anything on the agent API because that's not the Consul agent instance that ContainerPilot is registering with. You probably want to be checking `/v1/health/service/<service>?pass` if you're trying to find out which instances are registered and healthy.

**Comment by cheapRoc** [comment]
@vrenjith Pruning issues, is there anything else here for us to look at or discuss?
