### ISSUE TITLE
split publish/subscribe behavior to better-leverage context

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#476]
Cancelling jobs, watches, servers, etc. has been a bit of a bug farm. We don't really leverage `context` as much as we probably could, but any use of this needs to make sure we're sending messages back like stopping/stopped and deregistering from the event bus.

I've worked up a preliminary design that splits the `EventHandler` into separate `Publisher` and `Subscriber` types and uses `context.CancelFunc` as a means of signaling shutdown instead of publishing an event. This _seems_ to work ok and I think will be subtly simpler in the long run.

Here's the worked demo: https://gist.github.com/tgross/6b0e32a85157c045718ee2ef5d3a8da6
If you `go run main.go 1000` this will run for 1000ms and then exit cleanly. It has the pub/sub types, an implementation of watch (pub-only), metric (sub-only), and job (pub+sub).

cc @cheapRoc

**Comment by tgross** [comment]
Updated the worked demo example here: https://gist.github.com/tgross/b167a2b1d4a5b727643d6e25f9962553

This one handles signals (SIGTERM and SIGINT, plus SIGHUP for reloads) rather than having a fixed time interval.

**Comment by cheapRoc** [comment]
There's a lot of work sitting behind this and I definitely feel the urge to complete what I've put in so far. 

At the moment I'm stuck attempting to uncover the reason why CP is not exiting when all jobs have completed cleanly. The primary integration test where this was uncovered is running the following (`test_envvars`)...

```json5
{
  consul: "127.0.0.1:8500",
  jobs: [
    {
      name: "testenvvar",
      port: 8500,
      exec: "env",
      health: {
        exec: "true",
        interval: 10,
        ttl: 25
      }
    }
  ]
}
```

This will halt execution and exits cleanly on master so I know the call stack the bug is in but not the specific code that's causing it. When this fires on my branch, it's still blocking on the `WaitGroup`, which is puzzling since de-registration should have occurred for the `Job` after the `Command` exits.

Still in flux.

**Comment by cheapRoc** [comment]
Ok, just as a note, it looks like the control server is not being shut down when a job exits cleanly/successfully. This makes sense because the existing implementation doesn't `Unregister` itself from the EventBus. Now we're getting somewhere...

**Comment by cheapRoc** [comment]
Another note, I'm on a good path now and down to a single failing integration test, `test_coprocess`.

**Comment by cheapRoc** [comment]
I cleaned up where I left off a few weeks ago and all tests are passing. Going to start rigorous testing in order to make sure this thing is truly stable.

**Comment by cheapRoc** [comment]
This has just been merged. Thanks for the proposal @tgross!

**Comment by cheapRoc** [comment]
No idea why I closed this without getting it released first.
