### ISSUE TITLE
Using containerpilot to register service in docker swarm, the registerd IP is not correct

### ISSUE THREAD

**Issue by biwugang** [joyent/containerpilot#524]
I'm trying to use ContainerPilot register each service to consul on docker Swarm env

but when I query the consul service, the registered service IP is not the docker container's IP.

docker-compose.yml file is as following:
`version: "3"

services:
    consul:
      image: progrium/consul:latest
      networks:
       - test-network
      command: ["-server", "-bootstrap-expect","3","-retry-join=consul", "-retry-join=consul","-retry-join=consul"]
      environment:
       - "CONSUL_BIND_INTERFACE=eth0"
      deploy:
          mode: replicated
          replicas: 3
    hello:
      image: hello:1.0
      networks:
       - test-network
      deploy:
          mode: replicated
          replicas: 2

networks:
    test-network :`

I use docker stack deploy to start the services: 
`docker stack deploy --compose-file docker-compose.yml test`

the hello service is the hello module in autopilotpattern/hello-world.
only change the containerpilot version from 3.0.0 to 3.5.1
the  containerpilot.json5 is:
`{
  consul: "consul:8500",
  jobs: [
    {
      name: "hello",
      exec: "node /opt/hello/index.js",
      port: 3001,
      health: {
        exec: "/usr/bin/curl -o /dev/null --fail -s http://localhost:3001/",
        interval: 3,
        ttl: 10
      }
    }
  ]
}`

the hello service information registered in consul is as following:
`[{"Node":"1ea155942ec1","Address":"10.1.2.3","ServiceID":"hello-79411d557881","ServiceName":"hello","ServiceTags":null,"ServiceAddress":"10.1.2.6","ServicePort":3001},{"Node":"1ea155942ec1","Address":"10.1.2.3","ServiceID":"hello-e00d26b8ed26","ServiceName":"hello","ServiceTags":null,"ServiceAddress":"10.1.2.6","ServicePort":3001}]`

10.1.2.3 is the consul container's IP
10.1.2.6 is the docker test_hello service virtual IP, not the hello container's IP

there are two hello service containers, and the IP address is: 10.1.2.7 and 10.1.2.8

**Comment by tianon** [comment]
I wasn't able to get your `docker-compose.yml` working as-is, but I was able to make a slightly simpler version to reproduce:
```yaml
version: "3"

services:
    consul:
        image: consul:1.0.0
        networks:
            - test-network
        environment:
            - "CONSUL_BIND_INTERFACE=eth0"
        deploy:
            mode: replicated
            replicas: 1

    hello:
        image: autopilotpattern/hello-world
        networks:
            - test-network
        deploy:
            mode: replicated
            replicas: 2

networks:
    test-network:
```
(where `autopilotpattern/hello-world` is built from an unmodified copy of https://github.com/autopilotpattern/hello-world/tree/7ceb618f9e03f36d63b578a1879e0d7a95c41826/hello)
```console
$ docker stack deploy --compose-file docker-compose.yml test
Creating network test_test-network
Creating service test_consul
Creating service test_hello
$ # then, once everything is actually running properly:
$ docker service ps --no-trunc --format '{{ .Name }}.{{ .ID }}' test_consul
test_consul.1.d0jxt8ceybxipymygsa9l9913
$ docker exec -it test_consul.1.d0jxt8ceybxipymygsa9l9913 curl http://localhost:8500/v1/catalog/service/hello
[
    {
        "ID": "bb86828e-9f6a-7c41-a437-f614f902e4de",
        "Node": "3965de1334cf",
        "Address": "10.0.0.3",
        "Datacenter": "dc1",
        "TaggedAddresses": {
            "lan": "10.0.0.3",
            "wan": "10.0.0.3"
        },
        "NodeMeta": {
            "consul-network-segment": ""
        },
        "ServiceID": "hello-1d52f3571447",
        "ServiceName": "hello",
        "ServiceTags": [],
        "ServiceAddress": "10.0.0.4",
        "ServicePort": 3001,
        "ServiceEnableTagOverride": false,
        "CreateIndex": 11,
        "ModifyIndex": 11
    },
    {
        "ID": "bb86828e-9f6a-7c41-a437-f614f902e4de",
        "Node": "3965de1334cf",
        "Address": "10.0.0.3",
        "Datacenter": "dc1",
        "TaggedAddresses": {
            "lan": "10.0.0.3",
            "wan": "10.0.0.3"
        },
        "NodeMeta": {
            "consul-network-segment": ""
        },
        "ServiceID": "hello-f38592c3b3f2",
        "ServiceName": "hello",
        "ServiceTags": [],
        "ServiceAddress": "10.0.0.4",
        "ServicePort": 3001,
        "ServiceEnableTagOverride": false,
        "CreateIndex": 7,
        "ModifyIndex": 7
    }
]
```

Docker is providing two IPs on `eth0` inside these containers:

```console
$ docker exec -it test_hello.1.kcxu4gp49tplil30uypxk0dmd ip address show dev eth0
55421: eth0@if55422: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:00:05 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.5/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.0.4/32 scope global eth0
       valid_lft forever preferred_lft forever
```

So it appears that ContainerPilot is picking up the second of these two IPs instead of the first, which throws off the registration (since that second IP is the shared VIP that Docker sets up for round-robin service access).

**Comment by tianon** [comment]
Found the bit of code at fault!

https://github.com/joyent/containerpilot/blob/6cfeff57541280d6181810211c66cef3bcb86ff9/config/services/ips.go#L281-L285

That'll sort the IPs by address, and since the VIP is created before any of the containers, it will almost always be a lower number (but not necessarily always).  It should, however, always be the second IP on the interface, so perhaps just removing that sorting behavior would be sufficient?

**Comment by misterbisson** [comment]
> > the registered service IP is not the docker container's IP
> So it appears that ContainerPilot is picking up the second of these two IPs instead of the first

What's the [`interfaces`](https://www.joyent.com/containerpilot/docs/configuration/configuration-file#interfaces) config value in the ContainerPilot config for these services? 

> Docker is providing two IPs on `eth0` inside these containers

Indeed. Both ContainerPilot and Consul offer mechanism to select interfaces that are more specific than the interface name. See https://www.joyent.com/containerpilot/docs/configuration/configuration-file#interfaces for ContainerPilot and Consul in 1.0 uses [`go-sockaddr`](https://github.com/hashicorp/go-sockaddr) to resolve the `-advertise` value.

**Comment by tianon** [comment]
@misterbisson very stock, right from the `hello-world` repo:

https://github.com/autopilotpattern/hello-world/blob/7ceb618f9e03f36d63b578a1879e0d7a95c41826/hello/containerpilot.json5

```json5
{
  consul: "consul:8500",
  jobs: [
    {
      name: "hello",
      exec: "node /opt/hello/index.js",
      port: 3001,
      health: {
        exec: "/usr/bin/curl -o /dev/null --fail -s http://localhost:3001/",
        interval: 3,
        ttl: 10
      }
    }
  ]
}
```

**Comment by tianon** [comment]
However, that document you've linked is a bit misleading, because it states that `eth0:inet6` should match the _first_ IPv6 address, when it will in fact match the lexicographically-sorted "first" IPv6 address if I'm reading the code correctly (and the default value in ContainerPilot is `eth0:inet`)

Am I right in assuming that the sorting will even apply to the index-based choices such as `eth0[0]`?

**Comment by tianon** [comment]
Actually, I don't think there _is_ a better solution to this even with a more advanced `interfaces` config value due to the lexicographical sorting, short of disabling Docker's VIP behavior entirely, because the VIP address and the non-VIP address are not guaranteed to sort lexicographically in any sane way, so a single config would have to be adapted for every container deployed, with foreknowledge of which IP Docker will happen to choose for that container.

I'd also argue that the lexicographical sorting is more harmful than helpful given that it violates the principle of least surprise, given that IP addresses already have a defined order on interfaces.

**Comment by tianon** [comment]
Worth noting as well is that due to not sorting, Consul already picks up the correct IP from `eth0` with just `CONSUL_BIND_INTERFACE=eth0`:

```console
$ docker exec -it test_consul.1.ep56yltd5du0udy29etwqnwmt sh
/ # ip address show dev eth0
55480: eth0@if55481: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:00:03 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.3/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.0.2/32 scope global eth0
       valid_lft forever preferred_lft forever
/ # consul catalog nodes
Node          ID        Address   DC
27f42b531f40  f97c5473  10.0.0.3  dc1
```

**Comment by cheapRoc** [comment]
This sounds along the lines of #503 so I'd like to get this cleared up. What's the latest summary on this issue?

I'd rather not change the internals of how ContainerPilot is sorting but I'd gladly match Consul's implementation if that works out.

> because the VIP address and the non-VIP address are not guaranteed to sort lexicographically in any sane way

Maybe [this comment](https://github.com/joyent/containerpilot/issues/503#issuecomment-328631754) holds a partial solution.

**Comment by tianon** [comment]
Yeah, changing to `endpoint_mode: dnsrr` works around this by not using/providing those VIP addresses at all (and instead using DNS for load-balancing / round-robin), but IMO that's not a full solution and is merely a workaround (especially since both Consul and `hostname --ip-address` do the right thing out-of-the-box, and it's only CP that's got this odd extra behavior of sorting IP addresses lexicographically).

**Comment by cheapRoc** [comment]
> especially since both Consul and hostname --ip-address do the right thing out-of-the-box, and it's only CP that's got this odd extra behavior of sorting IP addresses lexicographically

Ok, I'll officially add this to my list this week and see what Consul is doing that we're not. Thanks for confirming that @tianon.

**Comment by cheapRoc** [comment]
For whatever reason I've yet to replicate the Docker Swarm setup recommended [here](https://github.com/joyent/containerpilot/issues/524#issuecomment-340615325). The containers all come up but I'm not seeing multiple interfaces. This might be because I'm testing locally on my Mac. I'll spin up a KVM instance and test there next.

**Comment by biwugang** [comment]
after docker version is update to 18.03.
the service virtual IP will not be add to container eth0.
so, there is no such issue.

when docker version is blow 18.03.
in containerpilot.json, it can use interface setting to force use eth0[1], like:
      interfaces: [
        "eth0[1]",
        ]

so, I close this issue
